title: Lab Notebook
short-title: Log # this prepended to the page title
author: Manuel Pichardo M
website: https://manuelpm.me/Notebook/
description: >
  Online notebook for my research at TTU

github_username: manuelmarcano22
baseurl: "/Notebook"

permalink: /log/:year_:month/

# Build settings
markdown: kramdown
theme: jekyll-lab-notebook

plugins:
- jekyll-lab-notebook-plugins


jekyll-lab-notebook:
  home-page:
    -
      name: Log
      is_posts: true
      hidden: false
    -
      name: Miscellaneous
      dir: 'random/'
      hidden: true
 

# live reload options
livereload: true
reload_port: 5678

# prevent jekyll from exploding on Travis
exclude: [vendor]
