title: Example ELN
short-title: ELN # this prepended to the page title
author: Your Name
website: https://github.com/tlnagy/jekyll-lab-notebook
description: >
  This is a live demo of the jekyll-lab-notebook software.

twitter_username: example
github_username: example
baseurl: "/Notebook"

permalink: /log/:year_:month/

# Build settings
markdown: kramdown
theme: jekyll-lab-notebook

plugins:
- jekyll-lab-notebook-plugins

jekyll-lab-notebook:
  home-page:
    -
      name: Log
      is_posts: true
      hidden: false
    -
      name: Protocols
      dir: 'protocols/'
      hidden: true
    -
      name: Miscellaneous
      dir: 'random/'
      hidden: true

# live reload options
livereload: true
reload_port: 5678

# prevent jekyll from exploding on Travis
exclude: [vendor]
